# Generated by Django 2.2 on 2019-05-19 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
