# Generated by Django 2.2 on 2019-05-28 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20190528_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='popularity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gpu',
        ),
    ]
